### ISSUE TITLE
Cannot deserialize value of type `java.lang.String` from Object value 

### ISSUE THREAD

**Issue by Prajwalgn-07** [aws/serverless-java-container#846]
*To help us debug your issue fill in the basic information below using the options provided*

*Serverless Java Container version*: `2.0.1`

*Implementations:* `Spring Boot`

*Framework version:* `SpringBoot 3.2.4`

*Frontend service:* `REST API`

*Deployment method:* `Serverless Framework`

## Scenario
*Describe what you are trying to accomplish*

Hello I am creating a lambda function for my service. when I try to call my post API with the json body from lambda test console it is not able to deserialize it into the object which is defined in my code

## Expected behavior
*Describe how you would expect the application to behave*
When I pass the body as json input it should get deserialized and consumed in my spring boot application

## Actual behavior
*Describe what you are seeing instead*
It is throwing `java.lang.String` from Object value 

## Steps to reproduce
*Provide code samples we can use to reproduce the issue as part of our integration tests. If there is a public repository for the misbehaving application link to it here

Below is the test input given
```
{
  "resource": "/{proxy+}",
  "path": "/api/v1/inference",
  "body": {
    "model":"sketch",
    "sketch":{
    "params": {
        "seed": 12345,
        "max_seq_length": 512,
        "temperature": 1.0,
        "top_k": 1.0,
        "top_p": 0.5
    },
    "sketch": {
        "version": "4.0.0",
        "metadata": {
            "parent_project": "simple_11f5627d",
            "document_name": "Untitled",
            "component_name": "Untitled",
            "component_hierarchy": []
        },
        "name": "Test1",
        "type": "Sketch"
    }
    }
},
  "headers": {
    "Authorization": "Bearer <Removed Token>"
  },
  "httpMethod": "POST",
  "requestContext": {
   <Removed this since its not necessary for the issue>
  }
}
```

`StreamLambdaHandler`
```
public class StreamLambdaHandler implements RequestStreamHandler {
    private static final Logger logger = LoggerFactory.getLogger(StreamLambdaHandler.class);

    private static final SpringBootLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler;
    static {
        try {
            logger.info("Initializing SpringBootLambdaContainerHandler"+AwsProxyRequest.class);
            handler = SpringBootLambdaContainerHandler.getAwsProxyHandler(FusionAIServiceApplication.class);
        } catch (ContainerInitializationException e) {
            e.printStackTrace();
            throw new RuntimeException("Could not initialize Spring Boot application", e);
        }
    }

    @Override
    public void handleRequest(InputStream inputStream, OutputStream outputStream, Context context)
            throws IOException {
        logger.info("Handling request"+inputStream.toString());
        handler.proxyStream(inputStream, outputStream, context);
    }
}
```
Rest Mapping
```
    @PostMapping("/inference")
    public ServiceResponse modelInference(@RequestBody ServiceRequest serviceRequest, @RequestHeader Map<String, String> headers) {
    ......
```

## Full log output
*Paste the full log output from the Lambda function's CloudWatch logs*

Below is the stack trace
```
2024-04-20T09:41:05.847+05:30	at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:197) ~[aws-lambda-java-runtime-interface-client-2.4.2-linux-x86_64.jar:2.4.2]
2024-04-20T09:41:05.847+05:30
at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.main(AWSLambda.java:187) ~[aws-lambda-java-runtime-interface-client-2.4.2-linux-x86_64.jar:2.4.2]

at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.main(AWSLambda.java:187) ~[aws-lambda-java-runtime-interface-client-2.4.2-linux-x86_64.jar:2.4.2]
2024-04-20T09:41:05.848+05:30
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)

com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.String` from Object value (token `JsonToken.START_OBJECT`)
2024-04-20T09:41:05.848+05:30	at [Source: (ByteArrayInputStream); line: 1, column: 59] (through reference chain: com.amazonaws.serverless.proxy.model.AwsProxyRequest["body"])
2024-04-20T09:41:05.848+05:30
at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)

at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
2024-04-20T09:41:05.848+05:30	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1752)
2024-04-20T09:41:05.848+05:30	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1526)
2024-04-20T09:41:05.848+05:30	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1431)
2024-04-20T09:41:05.848+05:30	at com.fasterxml.jackson.databind.DeserializationContext.extractScalarFromObject(DeserializationContext.java:943)
2024-04-20T09:41:05.848+05:30	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseString(StdDeserializer.java:1424)
2024-04-20T09:41:05.848+05:30	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:48)
2024-04-20T09:41:05.848+05:30	at com.fasterxml.jackson.databind.deser.std.StringDeserializer.deserialize(StringDeserializer.java:11)
2024-04-20T09:41:05.848+05:30	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
2024-04-20T09:41:05.848+05:30	at com.fasterxml.jackson.module.afterburner.deser.SettableStringMethodProperty.deserializeAndSet(SettableStringMethodProperty.java:41)
2024-04-20T09:41:05.848+05:30	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:278)
2024-04-20T09:41:05.848+05:30	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
2024-04-20T09:41:05.848+05:30	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
2024-04-20T09:41:05.848+05:30	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2105)
2024-04-20T09:41:05.849+05:30	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1481)
2024-04-20T09:41:05.849+05:30	at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:257)
2024-04-20T09:41:05.849+05:30	at com.autodesk.fusion.fusionaiservice.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:36)
```

**Comment by Prajwalgn-07** [comment]
And yeah I tried setting the body value to string instead of the json input, and set the header 
```
  "headers": {
    "Authorization": "Bearer <Removed Token>",
    "Content-Type": "application/json"
  }
```
Then I am getting the HttpMediaTypeNotSupportedException which doesn't make sense
```
START RequestId: 1f2fab44-1d58-47a9-bad9-d9718ef5b497 Version: 3
2024-04-21T12:44:04.309Z  WARN 8 --- [fusion-ai-service] [           main] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.HttpMediaTypeNotSupportedException: Content-Type 'application/octet-stream' is not supported]
2024-04-21T12:44:04.309Z  INFO 8 --- [fusion-ai-service] [           main] c.a.s.p.internal.LambdaContainerHandler  : 127.0.0.1 null- null [09/04/2015:12:34:56Z] "POST /api/v1/inference HTTP/1.1" 415 - "-" "Custom User Agent String" combined
END RequestId: 1f2fab44-1d58-47a9-bad9-d9718ef5b497
REPORT RequestId: 1f2fab44-1d58-47a9-bad9-d9718ef5b497	Duration: 3.40 ms	Billed Duration: 4 ms	Memory Size: 512 MB	Max Memory Used: 154 MB	
```

And yeah I tested by locally bringing up the service using sam and . there it seems to be working fine

**Comment by mbfreder** [comment]
Thanks for raising this. We will look into it.

**Comment by Vandita2020** [comment]
Hey @Prajwalgn-07, 
I have tried to reproduce your issue and figure out the cause. In this case I think the issue is with your JSON file, and you were almost on the right path. If you can change setting `content-type` in `multiValueHeaders` instead of `headers`, something like mentioned below, this might work.
```
"multiValueHeaders":{
    "content-type":["application/json"]
  },
```
Please set this and let us know if you still get errors.
