### ISSUE TITLE
com.amazonaws.serverless.exceptions.InvalidRequestEventException: The incoming event is not a valid request from Amazon API Gateway or an Application Load Balancer

### ISSUE THREAD

**Issue by Prajwalgn-07** [aws/serverless-java-container#868]
*To help us debug your issue fill in the basic information below using the options provided*

*Serverless Java Container version*: `1.9.4`

*Implementations:* `Spring Boot 2`

*Framework version:* `2.7.18`

*Frontend service:* `REST API`

*Deployment method:* `Serverless Framework`

## Scenario
I am trying to call the lambda from the api-gateway. The service is getting triggered as per the logs but it fails with above exception

## Expected behavior
Call should go inside service handler and give proper response

## Actual behavior
com.amazonaws.serverless.exceptions.InvalidRequestEventException: The incoming event is not a valid request from Amazon API

## Steps to reproduce
`build.gradle`
```
plugins {
	id 'java'
	id 'org.springframework.boot' version '2.7.18'
	id 'io.spring.dependency-management' version '1.1.4'
}

apply from: 'dependencies.gradle'

group = 'com.<removed>'

java {
	toolchain {
		languageVersion.set(JavaLanguageVersion.of(11))
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
	configureEach {
		exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
		exclude group: 'org.springframework.boot', module: 'spring-boot-starter-log4j2'
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation('org.springframework.boot:spring-boot-starter-web') {
		exclude module: 'spring-boot-starter-logging'
	}
	testImplementation('org.mockito:mockito-junit-jupiter:' + libraryVersions.mockito)
	testImplementation('org.mockito:mockito-inline:' + libraryVersions.mockito)
	testImplementation('org.powermock:powermock-api-mockito2:' + libraryVersions.powerMockApi)
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation('org.junit.jupiter:junit-jupiter-engine')
	testImplementation('org.junit.jupiter:junit-jupiter-api')
	testImplementation('org.junit.jupiter:junit-jupiter-params')
	testImplementation('org.junit.vintage:junit-vintage-engine')
	compileOnly('org.projectlombok:lombok:'+ libraryVersions.lombok)
	annotationProcessor('org.projectlombok:lombok:'+ libraryVersions.lombok)
	implementation 'org.apache.logging.log4j:log4j-core:' + libraryVersions.log4jCore
	implementation 'org.apache.logging.log4j:log4j-api:' + libraryVersions.log4jCore
	implementation 'org.apache.logging.log4j:log4j-slf4j-impl:' + libraryVersions.log4jCore
	implementation 'com.google.guava:guava:' + libraryVersions.guava
	implementation 'org.bitbucket.b_c:jose4j:' + libraryVersions.jose4j
	implementation 'com.amazonaws.serverless:aws-serverless-java-container-springboot2:1.9.4'
}

tasks.named('test') {
	useJUnitPlatform()
}

tasks.register('buildZip', Zip) {
	from compileJava
	from processResources
	into('lib') {
		from configurations.runtimeClasspath
	}
}

build.dependsOn buildZip
```

`StreamLambdaHandler`
```
public class StreamLambdaHandler implements RequestStreamHandler {
    private static final Logger logger = LoggerFactory.getLogger(StreamLambdaHandler.class);

    private static final SpringBootLambdaContainerHandler<AwsProxyRequest, AwsProxyResponse> handler;
    static {
        try {
            logger.info("Initializing SpringBootLambdaContainerHandler"+AwsProxyRequest.class);
            handler = SpringBootLambdaContainerHandler.getAwsProxyHandler(ServiceApplication.class);
        } catch (ContainerInitializationException e) {
            throw new RuntimeException("Could not initialize Spring Boot application", e);
        }
    }

    @Override
    public void handleRequest(InputStream inputStream, OutputStream outputStream, Context context)
            throws IOException {
        handler.proxyStream(inputStream, outputStream, context);
    }
}
```

## Full log output
*Paste the full log output from the Lambda function's CloudWatch logs*

```
2024-05-03T21:59:41.679+05:30	2024-05-03 16:29:41.651 ERROR 8 --- [ main] c.a.s.p.i.LambdaContainerHandler : Error while handling request
2024-05-03T21:59:41.679+05:30
com.amazonaws.serverless.exceptions.InvalidRequestEventException: The incoming event is not a valid request from Amazon API Gateway or an Application Load Balancer

com.amazonaws.serverless.exceptions.InvalidRequestEventException: The incoming event is not a valid request from Amazon API Gateway or an Application Load Balancer
2024-05-03T21:59:41.679+05:30	at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequestReader.readRequest(AwsProxyHttpServletRequestReader.java:48) ~[aws-serverless-java-container-core-1.9.4.jar:?]
2024-05-03T21:59:41.679+05:30	at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequestReader.readRequest(AwsProxyHttpServletRequestReader.java:30) ~[aws-serverless-java-container-core-1.9.4.jar:?]
2024-05-03T21:59:41.679+05:30	at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:204) [aws-serverless-java-container-core-1.9.4.jar:?]
2024-05-03T21:59:41.679+05:30	at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:257) [aws-serverless-java-container-core-1.9.4.jar:?]
2024-05-03T21:59:41.679+05:30	at com.<Removed>.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:32) [task/:?]
2024-05-03T21:59:41.679+05:30	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
2024-05-03T21:59:41.679+05:30	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
2024-05-03T21:59:41.679+05:30	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
2024-05-03T21:59:41.679+05:30	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
2024-05-03T21:59:41.679+05:30	at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:383) [aws-lambda-java-runtime-0.2.0.jar:?]
2024-05-03T21:59:41.679+05:30	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:925) [aws-lambda-java-runtime-0.2.0.jar:?]
2024-05-03T21:59:41.679+05:30	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:268) [aws-lambda-java-runtime-0.2.0.jar:?]
2024-05-03T21:59:41.679+05:30	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:207) [aws-lambda-java-runtime-0.2.0.jar:?]
2024-05-03T21:59:41.679+05:30	at lambdainternal.AWSLambda.main(AWSLambda.java:196) [aws-lambda-java-runtime-0.2.0.jar:?]
2024-05-03T21:59:41.679+05:30	2024-05-03 16:29:41.679 ERROR 8 --- [ main] c.a.s.p.AwsProxyExceptionHandler : Called exception handler for:
2024-05-03T21:59:41.679+05:30	com.amazonaws.serverless.exceptions.InvalidRequestEventException: The incoming event is not a valid request from Amazon API Gateway or an Application Load Balancer
2024-05-03T21:59:41.679+05:30	at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequestReader.readRequest(AwsProxyHttpServletRequestReader.java:48) ~[aws-serverless-java-container-core-1.9.4.jar:?]
2024-05-03T21:59:41.679+05:30	at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequestReader.readRequest(AwsProxyHttpServletRequestReader.java:30) ~[aws-serverless-java-container-core-1.9.4.jar:?]
2024-05-03T21:59:41.679+05:30	at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:204) [aws-serverless-java-container-core-1.9.4.jar:?]
2024-05-03T21:59:41.679+05:30	at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:257) [aws-serverless-java-container-core-1.9.4.jar:?]
2024-05-03T21:59:41.679+05:30	at com.<Removed>.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:32) [task/:?]
2024-05-03T21:59:41.679+05:30	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
2024-05-03T21:59:41.679+05:30	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
2024-05-03T21:59:41.679+05:30	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
2024-05-03T21:59:41.679+05:30	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
2024-05-03T21:59:41.679+05:30	at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:383) [aws-lambda-java-runtime-0.2.0.jar:?]
2024-05-03T21:59:41.679+05:30	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:925) [aws-lambda-java-runtime-0.2.0.jar:?]
2024-05-03T21:59:41.679+05:30	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:268) [aws-lambda-java-runtime-0.2.0.jar:?]
2024-05-03T21:59:41.679+05:30	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:207) [aws-lambda-java-runtime-0.2.0.jar:?]
2024-05-03T21:59:41.679+05:30	at lambdainternal.AWSLambda.main(AWSLambda.java:196) [aws-lambda-java-runtime-0.2.0.jar:?]
2024-05-03T21:59:41.680+05:30	com.amazonaws.serverless.exceptions.InvalidRequestEventException: The incoming event is not a valid request from Amazon API Gateway or an Application Load Balancer
2024-05-03T21:59:41.680+05:30	at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequestReader.readRequest(AwsProxyHttpServletRequestReader.java:48)
2024-05-03T21:59:41.680+05:30	at com.amazonaws.serverless.proxy.internal.servlet.AwsProxyHttpServletRequestReader.readRequest(AwsProxyHttpServletRequestReader.java:30)
2024-05-03T21:59:41.680+05:30	at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:204)
2024-05-03T21:59:41.680+05:30	at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:257)
2024-05-03T21:59:41.680+05:30	at com.<Removed>.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:32)
2024-05-03T21:59:41.680+05:30	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-05-03T21:59:41.680+05:30	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2024-05-03T21:59:41.680+05:30	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2024-05-03T21:59:41.680+05:30	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2024-05-03T21:59:41.680+05:30	at lambdainternal.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:383)
2024-05-03T21:59:41.680+05:30	at lambdainternal.EventHandlerLoader$2.call(EventHandlerLoader.java:925)
2024-05-03T21:59:41.680+05:30	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:268)
2024-05-03T21:59:41.680+05:30	at lambdainternal.AWSLambda.startRuntime(AWSLambda.java:207)
2024-05-03T21:59:41.680+05:30	at lambdainternal.AWSLambda.main(AWSLambda.java:196)
```

**Comment by Prajwalgn-07** [comment]
It can be closed. The issue was resolved after changing the events type from `httpapi` to `http` in `serverless.yml`

Previous:
```
    events:
      - httpApi:
          path: /api/v1/inference
```
          
Fixed:
```
    events:
      - http:
          path: /api/v1/inference
```

**Comment by zhang12206** [comment]
Great, that solved my problem.
