### ISSUE TITLE
How to handle spring security with springboot serverless

### ISSUE THREAD

**Issue by jahidmomin** [aws/serverless-java-container#902]
*To help us debug your issue fill in the basic information below using the options provided*

*Serverless Java Container version*: ` 1.9,2.0.0-M1`

*Implementations:* ` Spring Boot 2 `

*Framework version:* `eg SpringBoot 2.2.6.RELEASE`

*Frontend service:* `REST API / HTTP API `

*Deployment method:* ` SAM

## Scenario
*I have production ready springboot application , shifting to serverless but when i am making request to my lambda rest api its returning 401 because i had spring security implementations *

## Expected behavior
*Able to execute all apis in my springboot app*

## Actual behavior
*returning 401 whenever hitting rest api in my application*

## Steps to reproduce
*It just an simple spring security jwt app wanted to host to serverless code is not public*

## Full log output
*2024-06-06 16:11:39.912 ERROR 16 --- [           main] c.a.s.p.internal.LambdaContainerHandler  : Error while handling request

java.lang.NullPointerException: Cannot invoke "javax.servlet.ServletConfig.getServletName()" because the return value of "javax.servlet.Servlet.getServletConfig()" is null
        at com.amazonaws.serverless.proxy.internal.servlet.FilterChainManager.putFilterChainCache(FilterChainManager.java:188)
        at com.amazonaws.serverless.proxy.internal.servlet.FilterChainManager.getFilterChain(FilterChainManager.java:135)
        at com.amazonaws.serverless.proxy.internal.servlet.AwsLambdaServletContainerHandler.getFilterChain(AwsLambdaServletContainerHandler.java:134)   
        at com.amazonaws.serverless.proxy.internal.servlet.AwsLambdaServletContainerHandler.doFilter(AwsLambdaServletContainerHandler.java:155)
        at com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler.handleRequest(SpringBootLambdaContainerHandler.java:180)
        at com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler.handleRequest(SpringBootLambdaContainerHandler.java:53)
        at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:214)
        at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:257)
        at com.infinitylearn.app.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:55)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at com.amazonaws.services.lambda.runtime.api.client.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:379)    
        at com.amazonaws.services.lambda.runtime.api.client.EventHandlerLoader$2.call(EventHandlerLoader.java:907)
        at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:239)
        at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:191)
        at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.main(AWSLambda.java:181)

2024-06-06 16:11:39.913 ERROR 16 --- [           main] c.a.s.proxy.AwsProxyExceptionHandler     : Called exception handler for:

java.lang.NullPointerException: Cannot invoke "javax.servlet.ServletConfig.getServletName()" because the return value of "javax.servlet.Servlet.getServletConfig()" is null
        at com.amazonaws.serverless.proxy.internal.servlet.FilterChainManager.putFilterChainCache(FilterChainManager.java:188)
        at com.amazonaws.serverless.proxy.internal.servlet.FilterChainManager.getFilterChain(FilterChainManager.java:135)
        at com.amazonaws.serverless.proxy.internal.servlet.AwsLambdaServletContainerHandler.getFilterChain(AwsLambdaServletContainerHandler.java:134)   
        at com.amazonaws.serverless.proxy.internal.servlet.AwsLambdaServletContainerHandler.doFilter(AwsLambdaServletContainerHandler.java:155)
        at com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler.handleRequest(SpringBootLambdaContainerHandler.java:180)
        at com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler.handleRequest(SpringBootLambdaContainerHandler.java:53)
        at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:214)
        at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:257)
        at com.infinitylearn.app.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:55)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at com.amazonaws.services.lambda.runtime.api.client.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:379)    
        at com.amazonaws.services.lambda.runtime.api.client.EventHandlerLoader$2.call(EventHandlerLoader.java:907)
        at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:239)
        at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:191)
        at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.main(AWSLambda.java:181)

java.lang.NullPointerException: Cannot invoke "javax.servlet.ServletConfig.getServletName()" because the return value of "javax.servlet.Servlet.getServletConfig()" is null
        at com.amazonaws.serverless.proxy.internal.servlet.FilterChainManager.putFilterChainCache(FilterChainManager.java:188)
        at com.amazonaws.serverless.proxy.internal.servlet.FilterChainManager.getFilterChain(FilterChainManager.java:135)
        at com.amazonaws.serverless.proxy.internal.servlet.AwsLambdaServletContainerHandler.getFilterChain(AwsLambdaServletContainerHandler.java:134)   
        at com.amazonaws.serverless.proxy.internal.servlet.AwsLambdaServletContainerHandler.doFilter(AwsLambdaServletContainerHandler.java:155)
        at com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler.handleRequest(SpringBootLambdaContainerHandler.java:180)
        at com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler.handleRequest(SpringBootLambdaContainerHandler.java:53)
        at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:214)
        at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:257)
        at com.infinitylearn.app.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:55)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at com.amazonaws.services.lambda.runtime.api.client.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:379)    
        at com.amazonaws.services.lambda.runtime.api.client.EventHandlerLoader$2.call(EventHandlerLoader.java:907)
        at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:239)
        at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:191)
        at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.main(AWSLambda.java:181)
*

```
logs
```

**Comment by deki** [comment]
Hi @jahidmomin,

could you please run `mvn dependency:tree` in your project and paste the output here?

**Comment by jahidmomin** [comment]
@deki Thanks for looking , I have resolved using servletapplication() using in handler while initialization & used @EnableWebMVC annotation over Main Application .  Now Jwt Filter working as well & unfortunately i have remove spring security .

**Comment by jahidmomin** [comment]
@deki Thanks for looking , I have resolved using servletapplication() using in handler while initialization & used @EnableWebMVC annotation over Main Application .  Now Jwt Filter working as well & unfortunately i have remove spring security .
