### ISSUE TITLE
Null Pointer While Setting Filter Post Startup Lambda Handler

### ISSUE THREAD

**Issue by jahidmomin** [aws/serverless-java-container#903]
*To help us debug your issue fill in the basic information below using the options provided*

*Serverless Java Container version*: `1.9.4`

*Implementations:* Spring Boot 2 `

*Framework version:* `eg SpringBoot 2.7.18`

*Frontend service:* `HTTP API `

*Deployment method:* `SAM`

## Scenario
Trying to hit the lambda with filter as given in samples*

## Expected behavior
*It should call my rest apis in side controller simillar like sample code*

## Actual behavior
*Giving Error*

## Steps to reproduce
*Build & Run in Local*

## Full log output
*java.lang.NullPointerException: Cannot invoke "javax.servlet.ServletConfig.getServletName()" because the return value of "javax.servlet.Servlet.getServletConfig()" is null
        at com.amazonaws.serverless.proxy.internal.servlet.FilterChainManager.putFilterChainCache(FilterChainManager.java:188)
        at com.amazonaws.serverless.proxy.internal.servlet.FilterChainManager.getFilterChain(FilterChainManager.java:135)
        at com.amazonaws.serverless.proxy.internal.servlet.AwsLambdaServletContainerHandler.getFilterChain(AwsLambdaServletContainerHandler.java:134)   
        at com.amazonaws.serverless.proxy.internal.servlet.AwsLambdaServletContainerHandler.doFilter(AwsLambdaServletContainerHandler.java:155)
        at com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler.handleRequest(SpringBootLambdaContainerHandler.java:180)
        at com.amazonaws.serverless.proxy.spring.SpringBootLambdaContainerHandler.handleRequest(SpringBootLambdaContainerHandler.java:53)
        at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:214)
        at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:257)
        at com.infinitylearn.app.StreamLambdaHandler.handleRequest(StreamLambdaHandler.java:54)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at com.amazonaws.services.lambda.runtime.api.client.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:379)    
        at com.amazonaws.services.lambda.runtime.api.client.EventHandlerLoader$2.call(EventHandlerLoader.java:907)
        at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:239)
*

```
logs
```

**Comment by deki** [comment]
This looks like a duplicate of #902, isn't it?

**Comment by jahidmomin** [comment]
@deki Thanks for looking , I have resolved using servletapplication() using in handler while initialization & used @EnableWebMVC annotation over Main Application .  Now Jwt Filter working as well post @EnableWebMvc.
